### ISSUE TITLE
Highlight active page in the navigation?

### ISSUE THREAD

**Issue by paulba** [koenbok/Cactus#150]
Hi! I'm new to cactus and python and I can't find an answer for this anywhere. How can I apply a custom css class on a navigation list item depending on the current active page? Do I need a plugin for this?

Thanks

**Comment by krallin** [comment]
Use the [`if_current_page` built-in template tag][0], like this:

    <li class="{% if_current_page '/index.html' ' active' 'inactive' %}">

This will apply the `active` CSS class if the current page is the one from `./pages/index.html`, and `inactive` otherwise.

Note that you can of course replace `'inactive'` with just `''` if you'd rather not apply anything in case  the current page isn't the one you're looking for.

  [0]: https://github.com/koenbok/Cactus/blob/13810eea26e4f82363a047238bf1b9ad1c66750a/cactus/template_tags.py#L95-L102
