### ISSUE TITLE
Cactus throws error on start

### ISSUE THREAD

**Issue by wilhelmy** [koenbok/Cactus#199]
Just installed cactus on OpenSuSE 13.1 via "easy_install cactus". Running it (with any amount of command line parameters) yields the following:
```
$ cactus 
Traceback (most recent call last):
  File "/usr/bin/cactus", line 9, in <module>
    load_entry_point('Cactus==3.3.0', 'console_scripts', 'cactus')()
TypeError: main() takes exactly 1 argument (0 given)
```

**Comment by krallin** [comment]
Fixed in 3.3.1 (which I just pushed to PyPi). 

This was a pretty overlook on my part: our CLI tests ran the `cli.py` module directly, which didn't surface the fact that the changes I made in `cli.py` broke the `entry_points` defined in `setup.py`.

I've added appropriate tests to ensure this doesn't break again!

Thanks for the report.
