### ISSUE TITLE
No Updates since 3 years?

### ISSUE THREAD

**Issue by guettli** [koenbok/Cactus#281]
No updates since 3 years?

Is this project dead?

**Comment by nathan-artist** [comment]
@guettli Yes, the project is dead. It is a great simple static site generator for small websites with an interesting history: it was made to be easy-to-use for designers, and it even had a GUI app for macOS. Even without the GUI app, it is very easy to use on the command line. I still use it often for one of my older websites. You just need to use it with an older version of Python (I use it with Python 2.7). But because the project is dead, it would not be the best software choice for new projects.

**Comment by JOduMonT** [comment]
based on ticket with the same question opened before and still open aka [277]3(https://github.com/eudicots/Cactus/issues/277) and even older [270](https://github.com/eudicots/Cactus/issues/270)
## I think you should look at something like Pelican or Lektor instead

**Comment by guettli** [comment]
I have no clue how to communicate this message ("I think you should look at something like Pelican or Lektor instead") to the users.

**Comment by JOduMonT** [comment]
> I have no clue how to communicate this message ("I think you should look at something like Pelican or Lektor instead") to the users.

Sorry I don't understand; 
I simply refer you to similar project (static website generator) which are also developed with python.

**Comment by guettli** [comment]
This was a joke. If I am the third person which asks about the status, then it might make sense to tell the world wide audience at the top of the README the current state of the project.

**Comment by negatendo** [comment]
If a project hasn't been updated in three years, where exactly do you get the expectation that they can or will update the readme? I'd like to remind you Cactus was open source software and not a commercial product, and as such its resources for development and maintenance are very different.

That said, since its open source software, here's how you do it: Modify the README yourself and then submit a pull request with the change. Best case scenario the change is accepted and you get what you want. Worst case scenario is your pull request sits there forever but everyone still sees it and your notes.

**Comment by guettli** [comment]
@negatendo I followed your advice and created a pull request to update the README: https://github.com/eudicots/Cactus/pull/282

**Comment by JOduMonT** [comment]
> This was a joke.

you not, joke are often related to our sense of humor and contextual and very hard to translate through the WorldWildWeb :)

**Comment by guettli** [comment]
you are right. I close this.

**Comment by JOduMonT** [comment]
> you are right. I close this.

Are you talking to me ?
I'm think I'm more left ;)

but in any case you should not case this issue since your PR as been rejected by the CI.
